name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build solution
      run: msbuild src/ArduWareApp/ArduWareApp.csproj /p:Configuration=Release

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: ArduWareApp
        path: src/ArduWareApp/bin/Release/ArduWareApp.exe
